[tool.poetry]
name = "parma-pars"
version = "0"
description = ""
authors = ["Grenui92"]
readme = "README.md"
packages = [{include = "parma_pars"}]

[tool.poetry.dependencies]
python = "^3.10"
scrapy = "^2.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
